# Generated by Django 4.1.7 on 2023-03-30 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_profile_picture_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(limit_choices_to={'role': 'SUBSCRIBER'}, to=settings.AUTH_USER_MODEL, verbose_name='suit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(upload_to='', verbose_name='profile picture'),
        ),
    ]
