# Generated by Django 4.1.7 on 2023-04-09 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0007_alter_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='section',
            field=models.CharField(choices=[('IT section', 'IT section'), ('MATH section', 'MATH section'), ('PHYS section', 'PHYS section'), ('Medicine section', 'Medicine section'), ('Sociology section', 'Sociology section')], default='None', max_length=30, verbose_name='Section'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.topic')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
