# Generated by Django 4.1.7 on 2023-04-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_studies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='studies',
            field=models.CharField(choices=[('IT license', 'IT license'), ('MATH license', 'MATH license'), ('PHYS license', 'PHYS license'), ('Medecine', 'Medecine'), ('Sociology license', 'Sociology license')], max_length=30, verbose_name='Studies'),
        ),
    ]
