# Generated by Django 4.1.7 on 2023-04-01 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_studies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='studies',
        ),
    ]
