# Generated by Django 4.1.7 on 2023-04-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_user_studies'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='studies',
            field=models.CharField(choices=[('IT license', 'IT license'), ('MATH license', 'MATH license'), ('PHYS license', 'PHYS license'), ('Medecine', 'Medecine'), ('Sociology license', 'Sociology license')], default='', max_length=30, verbose_name='Studies'),
        ),
    ]
