# Generated by Django 4.1.7 on 2023-04-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_topic_section_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='section',
            field=models.CharField(choices=[('IT section', 'IT section'), ('MATH section', 'MATH section'), ('PHYS section', 'PHYS section'), ('Medicine section', 'Medicine section'), ('Sociology section', 'Sociology section'), ('miscellaneous Topics', 'miscellaneous Topics')], default='None', max_length=30, verbose_name='Section'),
        ),
    ]
